---
deployment:
  tasks:
    - export DEPLOYPATH=/home/jigsawaf/hireground.thelightutors.com/
    - /bin/cp -R dist/* $DEPLOYPATH
    - /bin/chmod -R 644 $DEPLOYPATH
    - /bin/find $DEPLOYPATH -type d -exec chmod 755 {} \;
    - /bin/cp public/.htaccess $DEPLOYPATH 2>/dev/null || :
    - /bin/cp public/_redirects $DEPLOYPATH 2>/dev/null || :
